version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["python", "cat_quiz.py"]

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  mysql_data:
